title: High Scores
repository: stb-gaming/high-scores
url: https://stb-gaming.github.io/high-scores

#sky-games-images: https://sky-games-x.pages.dev/assets/img/games/
#sky-games-images: https://stb-gaming.github.io/sky-games/assets/img/games/
sky-games-images: https://stb-gaming.github.io/sky-games-images/

permalink: pretty
date-format: "%e %b %Y"
emptyarr: []

collections:
  scores:
    output: true
  players:
    output: true
  games:
    output: true
  lists:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
      comments: true
  - scope:
      path: ""
      type: lists
    values:
      permalink: /:title/
      comments: false
  - scope:
      path: ""
      type: posts
    values:
      comments: false
  - scope:
      path: ""
      type: pages
    values:
      comments: false


exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - yarn.lock
  - LICENSE
  - plan.md
  - README.md
  - gulpfile.js
  - gemfiles
  - src
  - package.json
  - package-lock.json


plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-redirect-to
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
  - jekyll-mention
  - jekyll-github-metadata

staticman:
  host: https://staticman.tumble1999.beanofficial.co
  git: github
  user: stb-gaming
  repo: high-scores
  branch: main