name: "Score Submission"
description: "Submit a high score"
title: "[Score]: "
labels: ["submission","score"]
assignees: ["actions-user"]
body:
  - type: input
    id: game
    attributes:
      label: Game
    validations:
      required: true
  - type: input
    id: author
    attributes:
      label: Player
    validations:
      required: true
  - type: input
    id: date
    attributes:
      label: Date (YYYY-MM-DD)
    validations:
      required: true
  - type: input
    id: score
    attributes:
      label: Score
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - PC
        - Mobile
        - TV
        - Games Console
        - Other
      default: 0
    validations:
      required: true
  - type: dropdown
    id: method
    attributes:
      label: Method
      options:
        - Vanilla
        - Userscript
        - Portal
        - Client
      default: 0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proof
      description: Upload Images, Videos, or paste urls to youtube, twitch, etc
    validations:
      required: true