name: Add Moderator

on:
  pull_request:
    types:
      - closed

jobs:
  edit-front-matter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Edit Front Matter
        run: |
          sed -i -E 's/score: '\''([0-9]+)'\''/score: \1/g' _scores/*.md
          sed -i -E 's/date: '\''([0-9]{4}-[0-9]{2}-[0-9]{2})'\''/date: \1/g' _scores/*.md
          AUTHOR=$(gh pr view ${{ github.event.number }} --json mergedBy | jq .mergedBy.login)
          NEW_FILES=$(gh pr view ${{ github.event.number }} --json files | jq -r '.files[].path'| grep '_scores/.*\.md')

          for FILE in $NEW_FILES; do
            awk -v author="$AUTHOR" '/^---/ && !found {print; print "mod: " author; found=1; next} 1' $FILE > temp && mv temp $FILE
          done

      - name: Push Changes
        run: |
         git checkout main
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Add moderator"
          git pull
          git push origin main

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
