name: Add Moderator

on:
  pull_request:
    types:
      - closed

jobs:
  edit-front-matter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39

      - name: Edit Front Matter
        if: steps.changed-files.any_changed == 'true'
        run: |
          AUTHOR=$(gh pr view ${{ github.event.number }} --json mergedBy | jq .mergedBy.login)

          for FILE in ${{ steps.changed-files.outputs.all_changed_files }}; do
            sed -i "/---/!b;n;i mod: $AUTHOR" $FILE
          done

      - name: Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Add moderator"
          git push -f

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
