name: Create Score

on:
  workflow_dispatch:
    inputs:
      game:
        description: 'Game ID'
        required: true
      author:
        description: 'Player name'
        required: true
      date:
        description: 'Date (YYYY-MM-DD)'
        required: true
      score:
        description: 'Score'
        required: true
      platform:
        description: 'Platform'
        required: true
      method:
        description: 'Method'
        required: true
      youtube:
        description: 'YouTube Video ID'
        required: false
      image:
        description: 'Image URL'
        required: false



jobs:
  generate_md:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Generate MD File
      run: |
        mkdir -p _scores
        echo "---" > _scores/${{ github.run_id }}.md
        echo "game: ${{ github.event.inputs.game }}" >> _scores/${{ github.run_id }}.md
        echo "author: ${{ github.event.inputs.author }}" >> _scores/${{ github.run_id }}.md
        echo "date: ${{ github.event.inputs.date }}" >> _scores/${{ github.run_id }}.md
        echo "score: ${{ github.event.inputs.score }}" >> _scores/${{ github.run_id }}.md
        echo "platform: ${{ github.event.inputs.platform }}" >> _scores/${{ github.run_id }}.md
        echo "method: ${{ github.event.inputs.method }}" >> _scores/${{ github.run_id }}.md
        echo "youtube: ${{ github.event.inputs.youtube }}" >> _scores/${{ github.run_id }}.md
        echo "image: ${{ github.event.inputs.image }}" >> _scores/${{ github.run_id }}.md
        echo "---" >> _scores/${{ github.run_id }}.md

    - name: Commit MD File
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add _scores/${{ github.run_id }}.md
        git commit -m "Add score for ${{ github.event.inputs.game }} by ${{ github.event.inputs.author }}"
        git push