name: Generate Game MD File

on:
  workflow_dispatch:
    inputs:
      gameid:
        description: 'Game ID'
        required: true
      title:
        description: 'Title'
        required: true
      description:
        description: 'Description'
        required: true
      developer:
        description: 'Developer'
        required: true
      brand:
        description: 'Brand'
        required: true
      archived:
        description: 'Archived Date (YYYY-MM-DD)'
        required: true
      menu:
        description: 'Menu Image URL'
        required: true




jobs:
  generate_md:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Generate MD File
      run: |
        mkdir -p _games
        echo "---" > _games/${{ github.event.inputs.gameid }}.md
        echo "title: ${{ github.event.inputs.title }}" >> _games/${{ github.event.inputs.gameid }}.md
        echo "description: ${{ github.event.inputs.description }}" >> _games/${{ github.event.inputs.gameid }}.md
        echo "developer: ${{ github.event.inputs.developer }}" >> _games/${{ github.event.inputs.gameid }}.md
        echo "brand: ${{ github.event.inputs.brand }}" >> _games/${{ github.event.inputs.gameid }}.md
        echo "archived: ${{ github.event.inputs.archived }}" >> _games/${{ github.event.inputs.gameid }}.md
        echo "menu: ${{ github.event.inputs.menu }}" >> _games/${{ github.event.inputs.gameid }}.md
        echo "---" >> _games/${{ github.event.inputs.gameid }}.md

    - name: Commit MD File
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add _games/${{ github.event.inputs.gameid }}.md
        git commit -m "Added ${{ github.event.inputs.title }}"
        git push
