name: Generate and Commit MD File

on:
  workflow_dispatch:
    inputs:
      gameid:
        description: 'Game ID'
        required: true
      title:
        description: 'Title'
        required: true
      description:
        description: 'Description'
        required: true
      developer:
        description: 'Developer'
        required: true
      brand:
        description: 'Brand'
        required: true
      splash:
        description: 'Splash'
        required: true
      gameplay:
        description: 'Gameplay'
        required: true
      archived:
        description: 'Archived Date (YYYY-MM-DD)'
        required: true
      image:
        description: 'Image'
        required: true
      menu:
        description: 'Menu Image URL'
        required: true
      category:
        description: 'Category'
        required: true
      scores_filter:
        description: 'Scores Filter'
        required: true
      play_link_title:
        description: 'Play Link Title'
        required: true
      play_link_url:
        description: 'Play Link URL'
        required: true
      wiki_link_url:
        description: 'Wiki Link URL (Optional)'
        required: false
      wiki_link_title:
        description: 'Wiki Link Title'
        required: false

jobs:
  generate_md:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Generate MD File
      run: |
        mkdir -p _games
        echo "---" > _games/${{ github.event.inputs.gameid }}.md
        echo "title: ${{ github.event.inputs.title }}" >> _games/${{ github.event.inputs.gameid }}.md
        echo "description: ${{ github.event.inputs.description }}" >> _games/${{ github.event.inputs.gameid }}.md
        echo "developer: ${{ github.event.inputs.developer }}" >> _games/${{ github.event.inputs.gameid }}.md
        echo "brand: ${{ github.event.inputs.brand }}" >> _games/${{ github.event.inputs.gameid }}.md
        echo "splash: ${{ github.event.inputs.splash }}" >> _games/${{ github.event.inputs.gameid }}.md
        echo "gameplay: ${{ github.event.inputs.gameplay }}" >> _games/${{ github.event.inputs.gameid }}.md
        echo "archived: ${{ github.event.inputs.archived }}" >> _games/${{ github.event.inputs.gameid }}.md
        echo "image: ${{ github.event.inputs.image }}" >> _games/${{ github.event.inputs.gameid }}.md
        echo "menu: ${{ github.event.inputs.menu }}" >> _games/${{ github.event.inputs.gameid }}.md
        echo "category: ${{ github.event.inputs.category }}" >> _games/${{ github.event.inputs.gameid }}.md
        echo "scores:" >> _games/${{ github.event.inputs.gameid }}.md
        echo "  filter: 'item.game == ${{ github.event.inputs.gameid }}'" >> _games/${{ github.event.inputs.gameid }}.md
        if [[ -n "${{ github.event.inputs.wiki_link_url }}" ]]; then
          echo "links:" >> _games/${{ github.event.inputs.gameid }}.md
          echo "  - title: Wiki" >> _games/${{ github.event.inputs.gameid }}.md
          echo "    url: ${{ github.event.inputs.wiki_link_url }}" >> _games/${{ github.event.inputs.gameid }}.md
        fi
        echo "---" >> _games/${{ github.event.inputs.gameid }}.md

    - name: Commit MD File
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add _games/${{ github.event.inputs.gameid }}.md
        git commit -m "Add info for ${{ github.event.inputs.title }}"
        git push
