name: FixFrontmatterTypes

on:
  push:
    paths:
      - '_scores/*'

jobs:
  fix-frontmatter-types:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Fix Frontmatter Types
      run: |
        sed -i -E 's/score: '\''([0-9]+)'\''/score: \1/g' _scores/*.md
        sed -i -E 's/date: '\''([0-9]{4}-[0-9]{2}-[0-9]{2})'\''/date: \1/g' _scores/*.md


    - name: Commit Changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add _scores/*.md
        git commit -m 'Fix frontmatter types 🛠️'
        git push
