name: Update Sky Games

on:
  deployment:
    # You can specify branches or environments to narrow it down
    # For example, to trigger on production deployments:
    environments:
      - github-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Sky Games Build
        # You may pin to the exact commit or the version.
        # uses: convictional/trigger-workflow-and-wait@f69fa9eedd3c62a599220f4d5745230e237904be
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          # The owner of the repository where the workflow is contained.
          owner: stb-gaming
          # The repository where the workflow is contained.
          repo: sky-games
          # The Github access token with access to the repository. It is recommended you put this token under secrets.
          github_token:  ${{ secrets.GH_TOKEN }}
          # The reference point. For example, you could use main.yml.
          workflow_file_name:  jekyll-gh-pages.yml
          ref: master
