name: Update Sky Games

on:
  deployment:
    # You can specify branches or environments to narrow it down
    # For example, to trigger on production deployments:
    environments:
      - github-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.BOT_ID }}
          private_key: ${{ secrets.BOT_PRIVATE }}
      - name: Trigger Sky Games Build
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/stb-gaming/sky-games/actions/workflows/jekyll-gh-pages.yml/dispatches \
            -d '{"ref":"master"}'
